### ISSUE TITLE
DML/DDL

### ISSUE THREAD

**Issue by shasn7** [cloudberrydb/cloudberrydb-site#165]
https://cloudberrydb.org/docs/sys-admin/backup-and-restore/

There is a sentence on the page: "This enables you to execute **DML** statements such as CREATE, ALTER, DROP, and TRUNCATE during backups,...".

I think there should be DDL instead of DML.

**Comment by tuhaihe** [comment]
Hi @shasn7 good catch! Would you like to submit one tiny pr to fix this when available? Appreciate it!
